# Dockerfile.snake
FROM nginxinc/nginx-unprivileged:alpine

COPY javascript-mini-game/snake/ /usr/share/nginx/html/

COPY javascript-mini-game/snake/snake.nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 8080/tcp
